version: '3.8'
services:
  dev-nest-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    ports:
      - 5432:5432
